name: 'GitHub Actions UP DATA'

on:
  push:
    branches: 
      - master
  schedule:
    #- cron: '0 23,2,5,8,11,14 * * *'
  workflow_dispatch:

jobs:
  up-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        run: 
          python up_data_group.py
